version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:47"
      timezone: Etc/UTC
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore(actions)
